name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from repo secrets/variables
        run: |
          cat > .env <<'EOF'
          BROWSER=${{ vars.BROWSER || 'firefox' }}
          HEADLESS=true
          BASE_URL=https://www.saucedemo.com
          DEFAULT_TIMEOUT=10
          SKIP_PRERUN_CHECK=false
          E2E_DEFAULT_USER=${{ secrets.E2E_DEFAULT_USER }}
          E2E_USERS_JSON=${{ secrets.E2E_USERS_JSON }}
          EOF
          echo "Created .env"
          echo "---- .env (safe preview) ----"
          grep -E '^(BROWSER|HEADLESS|BASE_URL|DEFAULT_TIMEOUT|SKIP_PRERUN_CHECK)=' .env || true
          echo "E2E_DEFAULT_USER present: $(grep -c '^E2E_DEFAULT_USER=' .env)"
          echo "E2E_USERS_JSON present:   $(grep -c '^E2E_USERS_JSON=' .env)"

      # Quickly check that the environment is visible to the process
      - name: Debug non-sensitive env
        run: |
          set -e
          echo "BROWSER=$BROWSER" || true
          echo "HEADLESS=$HEADLESS" || true
          echo "BASE_URL=$BASE_URL" || true
          test -f .env && echo ".env exists" || echo ".env missing"

      - name: Run unit tests
        run: |
          mkdir -p reports artifacts/screenshots
          pytest -m "not e2e" --maxfail=1 -q \
            --html=reports/unit_report.html --self-contained-html

      - name: Run E2E smoke tests
        run: |
          set -euo pipefail
          echo "Running smoke on ${BROWSER:-unset}, headless=${HEADLESS:-unset}"
          pytest -m "e2e and smoke" -q \
            --html=reports/e2e_report.html --self-contained-html

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            reports/**
            artifacts/screenshots/**
          if-no-files-found: warn
